# Generated by Django 6.0 on 2025-12-31 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data/Hora')),
                ('module', models.CharField(choices=[('auth', 'Autenticação'), ('empresas', 'Empresas'), ('funcionarios', 'Funcionários'), ('lancamentos', 'Lançamentos'), ('indices', 'Índices'), ('coefjam', 'Coef JAM'), ('relatorio', 'Relatórios'), ('configuracoes', 'Configurações'), ('billing', 'Billing'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='Módulo/App')),
                ('view_name', models.CharField(blank=True, max_length=255, verbose_name='View/Função')),
                ('url_path', models.CharField(blank=True, max_length=500, verbose_name='Caminho da URL')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CREATE', 'Criação'), ('UPDATE', 'Atualização'), ('DELETE', 'Exclusão'), ('VIEW', 'Visualização'), ('EXPORT', 'Exportação'), ('IMPORT', 'Importação'), ('REPORT', 'Relatório'), ('PAYMENT', 'Pagamento'), ('OTHER', 'Outra')], max_length=20, verbose_name='Ação')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID do Objeto')),
                ('object_repr', models.CharField(blank=True, max_length=500, verbose_name='Descrição do Objeto')),
                ('description', models.TextField(blank=True, verbose_name='Descrição Detalhada')),
                ('old_values', models.JSONField(blank=True, default=dict, verbose_name='Valores Anteriores')),
                ('new_values', models.JSONField(blank=True, default=dict, verbose_name='Novos Valores')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Mudanças')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('method', models.CharField(blank=True, max_length=10, verbose_name='Método HTTP')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='Código de Status HTTP')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Tipo de Conteúdo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='audit_logs__timesta_63825c_idx'), models.Index(fields=['user', '-timestamp'], name='audit_logs__user_id_64dfe5_idx'), models.Index(fields=['action', '-timestamp'], name='audit_logs__action_406b32_idx'), models.Index(fields=['module', '-timestamp'], name='audit_logs__module_7b7e44_idx')],
            },
        ),
    ]
