# Generated by Django 6.0 on 2025-12-31 13:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_pricingplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('BASIC', 'Básico'), ('PROFESSIONAL', 'Profissional'), ('ENTERPRISE', 'Empresarial')], max_length=20, unique=True, verbose_name='Tipo de Plano')),
                ('max_employees', models.IntegerField(blank=True, help_text='Deixe em branco para ilimitado', null=True, verbose_name='Máximo de Colaboradores')),
                ('has_advanced_dashboard', models.BooleanField(default=False, verbose_name='Dashboard Avançado')),
                ('has_custom_reports', models.BooleanField(default=False, verbose_name='Relatórios Personalizados')),
                ('has_pdf_export', models.BooleanField(default=False, verbose_name='Exportar PDF/Excel')),
                ('has_api', models.BooleanField(default=False, verbose_name='API Access')),
                ('support_level', models.CharField(choices=[('EMAIL', 'E-mail'), ('PRIORITY', 'Prioritário'), ('24_7', '24/7')], default='EMAIL', max_length=20, verbose_name='Nível de Suporte')),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço Mensal')),
                ('price_yearly', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço Anual')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['plan_type'],
            },
        ),
        migrations.AddField(
            model_name='billingcustomer',
            name='active_employees',
            field=models.IntegerField(default=0, verbose_name='Colaboradores Ativos'),
        ),
        migrations.AddField(
            model_name='billingcustomer',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='billing.plan', verbose_name='Plano'),
        ),
    ]
