# Generated by Django 6.0 on 2026-01-02 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_plan_billingcustomer_active_employees_and_more'),
        ('billing', '0003_trial_system'),
    ]

    operations = [
    ]
