# Generated by Django 6.0 on 2026-01-02 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_merge_20260102_1049'),
        ('empresas', '0002_alter_empresa_options_remove_empresa_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('sugestao', 'Sugestão'), ('elogio', 'Elogio'), ('reclamacao', 'Reclamação'), ('bug', 'Bug/Erro'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo de Feedback')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('email_resposta', models.EmailField(blank=True, max_length=254, verbose_name='Email para Resposta')),
                ('respondido', models.BooleanField(default=False, verbose_name='Respondido')),
                ('resposta', models.TextField(blank=True, verbose_name='Resposta do Time')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'ordering': ['-criado_em'],
            },
        ),
    ]
