# Generated by Django 5.0.6 on 2026-03-27 18:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_billingcustomer_override_price'),
        ('empresas', '0021_migrate_demissao_to_new_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoBPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex.: BPO Starter, BPO Pro, BPO Enterprise', max_length=100, verbose_name='Nome do Plano')),
                ('preco_por_cnpj', models.DecimalField(decimal_places=2, help_text='Valor cobrado mensalmente por cada empresa ativa no BPO', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço por CNPJ/mês (R$)')),
                ('max_funcionarios_por_cnpj', models.IntegerField(blank=True, help_text='Deixe em branco para ilimitado', null=True, verbose_name='Máx. funcionários por CNPJ')),
                ('max_usuarios_bpo', models.IntegerField(blank=True, help_text='Operadores que podem acessar o painel BPO. Deixe em branco para ilimitado', null=True, verbose_name='Máx. usuários do escritório')),
                ('max_meses_historico', models.IntegerField(blank=True, help_text='Deixe em branco para histórico ilimitado', null=True, verbose_name='Máx. meses de histórico')),
                ('trial_dias', models.IntegerField(default=7, help_text='Dias de uso gratuito ao ativar conta BPO', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Dias de trial')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plano BPO',
                'verbose_name_plural': 'Planos BPO',
                'ordering': ['preco_por_cnpj'],
            },
        ),
        migrations.CreateModel(
            name='ContaBPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_cobranca', models.IntegerField(default=5, help_text='Data de vencimento mensal (1 a 28)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)], verbose_name='Dia do mês para cobrança')),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Ativo'), ('suspended', 'Suspenso'), ('canceled', 'Cancelado')], default='trial', max_length=20, verbose_name='Status')),
                ('asaas_customer_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID cliente Asaas')),
                ('override_preco_por_cnpj', models.DecimalField(blank=True, decimal_places=2, help_text='Se informado, substitui o preço do plano para este BPO', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço especial por CNPJ (R$)')),
                ('override_max_usuarios_bpo', models.IntegerField(blank=True, help_text='Substitui o limite do plano para este BPO', null=True, verbose_name='Limite especial de usuários')),
                ('override_max_meses_historico', models.IntegerField(blank=True, help_text='Substitui o limite do plano para este BPO', null=True, verbose_name='Limite especial de histórico (meses)')),
                ('override_max_funcionarios_por_cnpj', models.IntegerField(blank=True, help_text='Substitui o limite do plano para este BPO', null=True, verbose_name='Limite especial de funcionários/CNPJ')),
                ('trial_ativo', models.BooleanField(default=True, verbose_name='Trial ativo')),
                ('trial_expira', models.DateField(blank=True, null=True, verbose_name='Trial expira em')),
                ('trial_used', models.BooleanField(default=False, verbose_name='Trial já utilizado')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa_bpo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='conta_bpo', to='empresas.empresa', verbose_name='Empresa do escritório')),
                ('plano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas', to='billing.planobpo', verbose_name='Plano BPO')),
            ],
            options={
                'verbose_name': 'Conta BPO',
                'verbose_name_plural': 'Contas BPO',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='billingcustomer',
            name='gerenciada_por_bpo',
            field=models.ForeignKey(blank=True, help_text='Se preenchido, a cobrança desta empresa é responsabilidade do escritório BPO vinculado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_customers', to='billing.contabpo', verbose_name='Gerenciada por BPO'),
        ),
        migrations.CreateModel(
            name='EmpresaBPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ativacao', models.DateField(auto_now_add=True, verbose_name='Data de ativação')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('suspended', 'Suspensa'), ('canceled', 'Cancelada')], default='active', max_length=20, verbose_name='Status')),
                ('permite_acesso_cliente', models.BooleanField(default=False, help_text='Se marcado, usuários desta empresa poderão fazer login na plataforma', verbose_name='Permitir acesso do cliente')),
                ('rateio_cobrado', models.DecimalField(blank=True, decimal_places=2, help_text='Valor proporcional cobrado ao ativar este CNPJ', max_digits=10, null=True, verbose_name='Rateio cobrado na ativação (R$)')),
                ('asaas_payment_id_rateio', models.CharField(blank=True, help_text='ID do pagamento avulso de rateio na Asaas', max_length=100, null=True, verbose_name='ID pagamento rateio (Asaas)')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('conta_bpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_gerenciadas', to='billing.contabpo', verbose_name='Conta BPO')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_bpo', to='empresas.empresa', verbose_name='Empresa cliente')),
            ],
            options={
                'verbose_name': 'Empresa gerenciada por BPO',
                'verbose_name_plural': 'Empresas gerenciadas por BPO',
                'ordering': ['-data_ativacao'],
            },
        ),
    ]
