# Generated by Django 5.0.6 on 2026-03-27 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_add_bpo_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='contabpo',
            name='billing_type',
            field=models.CharField(choices=[('BOLETO', 'Boleto'), ('PIX', 'PIX'), ('CREDIT_CARD', 'Cartão de Crédito')], default='BOLETO', help_text='Método de pagamento usado nas cobranças mensais', max_length=20, verbose_name='Forma de pagamento'),
        ),
        migrations.CreateModel(
            name='FaturaBPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.DateField(help_text='Primeiro dia do mês de referência', verbose_name='Mês de referência')),
                ('cnpjs_cobrados', models.IntegerField(verbose_name='CNPJs cobrados')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('asaas_payment_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID pagamento Asaas')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Pago'), ('overdue', 'Vencido'), ('canceled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('conta_bpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='billing.contabpo', verbose_name='Conta BPO')),
            ],
            options={
                'verbose_name': 'Fatura BPO',
                'verbose_name_plural': 'Faturas BPO',
                'ordering': ['-mes_referencia'],
                'unique_together': {('conta_bpo', 'mes_referencia')},
            },
        ),
    ]
