# Generated by Django 5.0.6 on 2026-03-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_add_fatura_bpo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresabpo',
            name='data_suspensao',
            field=models.DateField(blank=True, help_text='Preenchido automaticamente quando a empresa é suspensa', null=True, verbose_name='Data de suspensão'),
        ),
    ]
