# Generated by Django 5.1.4 on 2026-02-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0002_alter_configuracao_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
