# Generated by Django 6.0 on 2025-12-27 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_alter_empresa_options_remove_empresa_id_and_more'),
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
        migrations.AddField(
            model_name='funcionario',
            name='carteira_profissional',
            field=models.CharField(blank=True, max_length=20, verbose_name='Carteira Profissional'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cbo',
            field=models.CharField(blank=True, max_length=10, verbose_name='CBO'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data Nascimento'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='matricula',
            field=models.CharField(blank=True, max_length=20, verbose_name='Matrícula'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='serie_carteira',
            field=models.CharField(blank=True, max_length=10, verbose_name='Série Carteira'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_admissao',
            field=models.DateField(verbose_name='Data Admissão'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_demissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data Demissão'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='pis',
            field=models.CharField(blank=True, max_length=15, verbose_name='PIS'),
        ),
    ]
