# Generated by Django 5.0.6 on 2026-01-22 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0005_remove_unique_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='data_admissao',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='data_demissao',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='matricula',
        ),
    ]
