# Generated by Django 5.1.4 on 2026-08-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0007_alter_funcionario_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticoOrfaos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Diagnóstico de Órfãos',
                'verbose_name_plural': 'Diagnóstico de Dados Órfãos',
                'managed': False,
            },
        ),
    ]
