# Generated by Django 6.0 on 2025-12-27 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.CharField(max_length=7)),
                ('base_fgts', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_fgts', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pago', models.BooleanField(default=False)),
                ('data_pagto', models.DateField(blank=True, null=True)),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='empresas.empresa')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='funcionarios.funcionario')),
            ],
        ),
    ]
