# Generated by Django 6.0 on 2025-12-31 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0002_alter_lancamento_options_lancamento_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='pago_em',
            field=models.DateTimeField(blank=True, help_text='Data/hora em que foi registrado como pago no sistema', null=True, verbose_name='Marcado como pago em'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='data_pagto',
            field=models.DateField(blank=True, help_text='Data em que o FGTS foi efetivamente pago', null=True, verbose_name='Data de Pagamento'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='pago',
            field=models.BooleanField(default=False, help_text='FGTS foi pago?'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Pago'),
        ),
    ]
