# Generated by Django 6.0 on 2026-01-03 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0004_add_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lancamento',
            name='idx_lancamento_empresa_comp_pago',
        ),
        migrations.RemoveIndex(
            model_name='lancamento',
            name='idx_lancamento_empresa_pago',
        ),
        migrations.RemoveIndex(
            model_name='lancamento',
            name='idx_lancamento_competencia_pago',
        ),
        migrations.RemoveIndex(
            model_name='lancamento',
            name='idx_lancamento_func_competencia',
        ),
        migrations.RemoveIndex(
            model_name='lancamento',
            name='idx_lancamento_func_criado',
        ),
        migrations.RemoveIndex(
            model_name='lancamento',
            name='idx_lancamento_empresa_func',
        ),
        migrations.RemoveIndex(
            model_name='lancamento',
            name='idx_lancamento_competencia',
        ),
        migrations.RemoveIndex(
            model_name='lancamento',
            name='idx_lancamento_pago',
        ),
    ]
