# Generated by Django 5.0.6 on 2026-01-12 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0006_add_parcela_13_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='parcela_13',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '13º Salário - 1ª Parcela'), (2, '13º Salário - 2ª Parcela')], help_text='Se preenchido, indica que é uma das 2 parcelas do 13º salário', null=True),
        ),
        migrations.CreateModel(
            name='ConferenciaLancamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente de Conferência'), ('CONFERIDO', 'Conferido - OK'), ('PROBLEMA', 'Conferido - Com Problema'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=20)),
                ('data_conferencia', models.DateTimeField(blank=True, null=True)),
                ('valor_conferido', models.DecimalField(blank=True, decimal_places=2, help_text='Valor conferido manualmente (se diferente de calculado)', max_digits=15, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('conferido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conferencias_lancamentos', to=settings.AUTH_USER_MODEL)),
                ('lancamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conferencia', to='lancamentos.lancamento')),
            ],
            options={
                'verbose_name': 'Conferência de Lançamento',
                'verbose_name_plural': 'Conferências de Lançamentos',
                'db_table': 'lancamentos_conferencia',
            },
        ),
    ]
