# Generated by Django 5.0.6 on 2026-01-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_alter_funcionario_id'),
        ('lancamentos', '0007_alter_lancamento_id_alter_lancamento_parcela_13_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lancamento',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='parcela_13',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, 'Competência Normal (01-12)'), (1, '13º Salário - 1ª Parcela'), (2, '13º Salário - 2ª Parcela')], help_text='Se preenchido, indica que é uma das 2 parcelas do 13º salário', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='lancamento',
            unique_together={('funcionario', 'competencia', 'parcela_13')},
        ),
    ]
