# Generated by Django 5.1.4 on 2026-01-27 12:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0008_alter_lancamento_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='adicionais',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Adicionais salariais', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='desconto_inss',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Desconto de INSS', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='desconto_ir',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Desconto de IR', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='desconto_sindical',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Contribuição sindical', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='horas_extras',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Valores variáveis como horas extras', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='conferencialancamento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
