# Generated by Django 5.1.4 on 2026-02-05 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0008_alter_transferenciafuncionario_data_transferencia'),
        ('funcionarios', '0006_remove_funcionario_data_admissao_and_more'),
        ('lancamentos', '0009_lancamento_adicionais_lancamento_desconto_inss_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lancamento',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='vinculo',
            field=models.ForeignKey(blank=True, help_text='Opcional. Identifica a "cadeira" (vínculo) do funcionário para esta competência.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='empresas.funcionariovinculo'),
        ),
        migrations.AlterUniqueTogether(
            name='lancamento',
            unique_together={('empresa', 'funcionario', 'competencia', 'parcela_13', 'vinculo')},
        ),
    ]
