# Generated by Django 5.0.6 on 2026-03-12 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0018_populate_vinculo_status'),
        ('lancamentos', '0010_alter_lancamento_unique_together_lancamento_vinculo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacaoLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='importacoes/lancamentos/')),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Aguardando'), ('processing', 'Processando'), ('done', 'Concluído'), ('error', 'Erro')], default='pending', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('resultado_json', models.JSONField(blank=True, null=True)),
                ('mensagem_erro', models.TextField(blank=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresas.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importacoes_lancamento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Importação de Lançamentos',
                'verbose_name_plural': 'Importações de Lançamentos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
