# Generated by Django 5.0.6 on 2026-03-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0011_importacaolancamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacaolancamento',
            name='linhas_processadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importacaolancamento',
            name='linhas_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
