# Generated by Django 5.0.6 on 2026-03-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0012_importacaolancamento_linhas_processadas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacaolancamento',
            name='preview_resultado',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importacaolancamento',
            name='status',
            field=models.CharField(choices=[('preview', 'Aguardando confirmação'), ('pending', 'Aguardando'), ('processing', 'Processando'), ('done', 'Concluído'), ('error', 'Erro')], default='pending', max_length=20),
        ),
    ]
