# Generated by Django 5.0.6 on 2026-03-25 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0013_importacaolancamento_preview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='importacaolancamento',
            name='aplicar_jam',
            field=models.BooleanField(default=False, help_text='Aplica juros acumulados (JAM) até a data de referência sobre o valor FGTS importado.', verbose_name='Aplicar correção JAM'),
        ),
        migrations.AddField(
            model_name='importacaolancamento',
            name='data_referencia_jam',
            field=models.DateField(blank=True, help_text='Data até a qual o JAM é calculado. Se em branco, usa a data de hoje.', null=True, verbose_name='Data de referência JAM'),
        ),
        migrations.AddField(
            model_name='importacaolancamento',
            name='recalcular_fgts',
            field=models.BooleanField(default=True, help_text='True = forçar 8% da base; False = manter o valor VALOR_FGTS do arquivo.', verbose_name='Recalcular FGTS'),
        ),
        migrations.CreateModel(
            name='ImportacaoResponsabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recalcular_fgts_escolha', models.BooleanField()),
                ('aplicar_jam_escolha', models.BooleanField()),
                ('data_referencia_jam_escolha', models.DateField(blank=True, null=True)),
                ('aceite_responsabilidade', models.BooleanField(default=False)),
                ('texto_termos', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('linhas_valor_do_arquivo', models.IntegerField(default=0)),
                ('linhas_jam_aplicado', models.IntegerField(default=0)),
                ('importacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responsabilidade', to='lancamentos.importacaolancamento')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsabilidades_importacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Responsabilidade de Importação',
                'verbose_name_plural': 'Responsabilidades de Importação',
            },
        ),
    ]
