# Generated by Django 5.0.6 on 2026-03-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0019_empresa_validar_meses_parcela_13'),
        ('funcionarios', '0007_alter_funcionario_id'),
        ('lancamentos', '0014_importacao_opcoes_responsabilidade'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lancamento',
            index=models.Index(fields=['empresa', 'competencia'], name='idx_lanc_empresa_comp'),
        ),
        migrations.AddIndex(
            model_name='lancamento',
            index=models.Index(fields=['funcionario', 'competencia'], name='idx_lanc_func_comp'),
        ),
        migrations.AddIndex(
            model_name='lancamento',
            index=models.Index(fields=['vinculo', 'competencia', 'parcela_13'], name='idx_lanc_vinc_comp_p13'),
        ),
        migrations.AddIndex(
            model_name='lancamento',
            index=models.Index(fields=['empresa', 'competencia', 'pago'], name='idx_lanc_emp_comp_pago'),
        ),
    ]
