# Generated by Django 5.0.6 on 2026-05-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0016_fonte_confirmacao_importacao_re_extrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importacaoextratoanalitico',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='importacaore',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
