# Generated by Django 5.0.6 on 2026-06-09 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0022_add_importar_re_sefip_extrato_cef'),
        ('lancamentos', '0017_alter_importacaoextratoanalitico_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametros_json', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Aguardando'), ('processing', 'Processando'), ('done', 'Concluído'), ('error', 'Erro')], default='pending', max_length=20)),
                ('resultado_json', models.JSONField(blank=True, null=True)),
                ('avisos_json', models.JSONField(blank=True, null=True)),
                ('mensagem_erro', models.TextField(blank=True)),
                ('total_lancamentos', models.IntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresas.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorio_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarefa de Relatório',
                'verbose_name_plural': 'Tarefas de Relatório',
                'ordering': ['-criado_em'],
            },
        ),
    ]
