# Generated by Django 6.0 on 2025-12-30 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_alter_empresa_options_remove_empresa_id_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='empresas_permitidas',
            field=models.ManyToManyField(blank=True, related_name='usuarios_permitidos', to='empresas.empresa', verbose_name='Empresas permitidas'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_multi_empresa',
            field=models.BooleanField(default=False, verbose_name='Gestor multiempresas'),
        ),
    ]
