# Generated by Django 5.0.6 on 2026-01-24 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_grupoempresa_empresafeature_funcionariovinculo_and_more'),
        ('usuarios', '0003_alter_usuario_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaUsuarioRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('gestor', 'Gestor'), ('operador', 'Operador')], max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_roles', to='empresas.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_empresas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permissão de Usuário por Empresa',
                'verbose_name_plural': 'Permissões de Usuário por Empresa',
                'unique_together': {('usuario', 'empresa')},
            },
        ),
    ]
