# Generated by Django 5.1.4 on 2026-02-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_email_confirmation'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS usuarios_usuario_empresas_permitidas (
                id bigserial PRIMARY KEY,
                usuario_id integer NOT NULL REFERENCES usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED,
                empresa_id integer NOT NULL REFERENCES empresas_empresa(id) DEFERRABLE INITIALLY DEFERRED,
                UNIQUE (usuario_id, empresa_id)
            );

            CREATE TABLE IF NOT EXISTS usuarios_usuario_groups (
                id bigserial PRIMARY KEY,
                usuario_id integer NOT NULL REFERENCES usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED,
                group_id integer NOT NULL REFERENCES auth_group(id) DEFERRABLE INITIALLY DEFERRED,
                UNIQUE (usuario_id, group_id)
            );

            CREATE TABLE IF NOT EXISTS usuarios_usuario_user_permissions (
                id bigserial PRIMARY KEY,
                usuario_id integer NOT NULL REFERENCES usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED,
                permission_id integer NOT NULL REFERENCES auth_permission(id) DEFERRABLE INITIALLY DEFERRED,
                UNIQUE (usuario_id, permission_id)
            );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='empresausuariorole',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
