"""
Django settings for fgtsweb project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carregar variáveis de ambiente do arquivo .env (sem sobrescrever env do runtime)
load_dotenv(BASE_DIR / '.env', override=False)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Compat: aceita tanto SECRET_KEY/DEBUG quanto DJANGO_SECRET_KEY/DJANGO_DEBUG.
SECRET_KEY = (
    os.getenv('DJANGO_SECRET_KEY')
    or os.getenv('SECRET_KEY')
    or None
)
if not SECRET_KEY:
    raise ImproperlyConfigured('SECRET_KEY ou DJANGO_SECRET_KEY deve ser definida nas variáveis de ambiente.')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = (os.getenv('DJANGO_DEBUG') or os.getenv('DEBUG') or 'False') == 'True'

ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', 'fgts.bildee.com.br,localhost,127.0.0.1').split(',')

# URL pública do sistema (usada em links enviados por email quando não há request).
# Ex.: https://fgts.bildee.com.br
SITE_URL = (os.getenv('SITE_URL') or '').strip().rstrip('/')

# CSRF trusted origins for HTTPS
CSRF_TRUSTED_ORIGINS = [
    'https://fgts.bildee.com.br',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]


# Configuração do tipo de primary key padrão para todos os models.
# Observação: o projeto possui histórico misto (AutoField/BigAutoField).
# Padronizado em BigAutoField e geradas migrações de alinhamento por app.
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'billing',
    'empresas',
    'funcionarios',
    'lancamentos',
    'usuarios',
    'configuracoes',
    'indices',
    'coefjam',
    'audit_logs',
    'monitoring',
    'emails',
    'django_apscheduler',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'audit_logs.middleware.AuditLogsMiddleware',
    'billing.middleware.TrialWarningMiddleware',
    'monitoring.middleware.PerformanceTrackingMiddleware',
]

ROOT_URLCONF = 'fgtsweb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'billing.context_processors.current_pricing',
                'empresas.context_processors.is_admin_empresa',
                'empresas.context_processors.sefip_feature',
                'billing.context_processors.conta_bpo_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'fgtsweb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Produção: configure o Postgres do Supabase via variáveis de ambiente.
# Suporte a DATABASE_URL (postgres://user:pass@host:port/db) ou variáveis separadas.
SUPABASE_URL = os.getenv('SUPABASE_DATABASE_URL') or os.getenv('DATABASE_URL')
SUPABASE_HOST = os.getenv('SUPABASE_HOST')
SUPABASE_DB = os.getenv('SUPABASE_DB')
SUPABASE_USER = os.getenv('SUPABASE_USER')
SUPABASE_PASSWORD = os.getenv('SUPABASE_PASSWORD')
SUPABASE_PORT = os.getenv('SUPABASE_PORT', '6543')  # Porta 6543 (pooler) por padrão
# Supabase REST API (para leitura quando conexão Postgres não estiver configurada)
SUPABASE_API_URL = os.getenv('SUPABASE_URL')  # ex: https://xyzcompany.supabase.co
SUPABASE_API_KEY = os.getenv('SUPABASE_KEY')  # service_role ou anon conforme necessidade

# Configurar banco de dados
missing_vars = []
for var_name, var_value in [
    ("SUPABASE_HOST", SUPABASE_HOST),
    ("SUPABASE_DB", SUPABASE_DB),
    ("SUPABASE_USER", SUPABASE_USER),
    ("SUPABASE_PASSWORD", SUPABASE_PASSWORD),
]:
    if not var_value:
        missing_vars.append(var_name)

if missing_vars:
    import sys
    if not DEBUG:
        print(f"\n[ERRO CRÍTICO] Variáveis de ambiente do banco Supabase ausentes: {', '.join(missing_vars)}", file=sys.stderr)
        print("Abortando inicialização do Django. Corrija o ambiente para evitar fallback para SQLite.", file=sys.stderr)
        sys.exit(1)

    print(
        f"\n[AVISO] Variáveis do Supabase ausentes ({', '.join(missing_vars)}). Usando SQLite em desenvolvimento.",
        file=sys.stderr,
    )
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'HOST': SUPABASE_HOST,
            'PORT': int(SUPABASE_PORT),
            'NAME': SUPABASE_DB,
            'USER': SUPABASE_USER,
            'PASSWORD': SUPABASE_PASSWORD,
            'OPTIONS': {
                'sslmode': 'require',
            },
        }
    }

# Modelo de usuário customizado
AUTH_USER_MODEL = 'usuarios.Usuario'

# Redirecionamentos de autenticação
LOGIN_REDIRECT_URL = 'dashboard'
LOGIN_URL = 'login'
LOGOUT_REDIRECT_URL = 'home'

# Sessao: expira apos 15 minutos de inatividade
SESSION_COOKIE_AGE = 15 * 60
SESSION_SAVE_EVERY_REQUEST = True

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Security settings para produção
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000  # 1 ano
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

# Email Configuration (Brevo/Sendinblue)
# https://docs.djangoproject.com/en/6.0/topics/email/

EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp-relay.brevo.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@bildee.com.br')
SERVER_EMAIL = DEFAULT_FROM_EMAIL  # Para emails de erro do servidor

# Logging
# - Erros 500 aparecem em django.request (inclui Django Admin)
# - Arquivo: FGTS/logs/django.log
LOG_LEVEL = os.getenv('DJANGO_LOG_LEVEL', 'WARNING').upper()
LOG_SQL = os.getenv('DJANGO_LOG_SQL', 'False') == 'True'

LOG_DIR = BASE_DIR / 'logs'
os.makedirs(LOG_DIR, exist_ok=True)
LOG_FILE = LOG_DIR / 'django.log'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': str(LOG_FILE),
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': LOG_LEVEL,
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG' if LOG_SQL else 'WARNING',
            'propagate': False,
        },
        'funcionarios': {
            'handlers': ['console', 'file'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'lancamentos': {
            'handlers': ['console', 'file'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'empresas': {
            'handlers': ['console', 'file'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'billing': {
            'handlers': ['console', 'file'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
    },
}
