# Generated by Django 6.0 on 2026-01-03 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacao', models.CharField(choices=[('relatorio_competencia', 'Relatório por Competência'), ('importacao_funcionarios', 'Importação de Funcionários'), ('exportacao_csv', 'Exportação CSV'), ('exportacao_pdf', 'Exportação PDF'), ('calculo_fgts', 'Cálculo FGTS'), ('geracao_lancamentos', 'Geração de Lançamentos'), ('importacao_lancamentos', 'Importação de Lançamentos'), ('outro', 'Outro')], max_length=50)),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('erro', 'Erro'), ('timeout', 'Timeout')], default='sucesso', max_length=20)),
                ('empresa_id', models.IntegerField(blank=True, null=True, verbose_name='ID da Empresa')),
                ('tempo_inicio', models.DateTimeField(auto_now_add=True)),
                ('tempo_final', models.DateTimeField(blank=True, null=True)),
                ('duracao_segundos', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('entrada_dados', models.JSONField(blank=True, default=dict, help_text='Parâmetros de entrada')),
                ('saida_dados', models.JSONField(blank=True, default=dict, help_text='Dados de saída (resumido)')),
                ('mensagem_erro', models.TextField(blank=True, help_text='Mensagem de erro se houver')),
                ('ip_cliente', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Performance Log',
                'verbose_name_plural': 'Performance Logs',
                'ordering': ['-tempo_inicio'],
                'indexes': [models.Index(fields=['operacao', '-tempo_inicio'], name='monitoring__operaca_140c84_idx'), models.Index(fields=['usuario', '-tempo_inicio'], name='monitoring__usuario_adb8c9_idx'), models.Index(fields=['empresa_id', '-tempo_inicio'], name='monitoring__empresa_1a800a_idx'), models.Index(fields=['status', '-tempo_inicio'], name='monitoring__status_9e8712_idx')],
            },
        ),
    ]
