# Generated by Django 6.0 on 2025-12-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoefJam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField()),
                ('competencia', models.CharField(max_length=7)),
                ('valor', models.DecimalField(decimal_places=8, max_digits=12)),
            ],
        ),
    ]
