# Generated by Django 6.0 on 2026-01-03 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coefjam', '0002_add_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='coefjam',
            name='idx_coefjam_competencia',
        ),
        migrations.RemoveIndex(
            model_name='coefjam',
            name='idx_coefjam_data_comp',
        ),
        migrations.RemoveIndex(
            model_name='coefjam',
            name='idx_coefjam_data_desc',
        ),
    ]
