# Generated by Django 5.0.6 on 2026-01-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coefjam', '0003_remove_coefjam_idx_coefjam_competencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coefjam',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
