# Generated by Django 6.0 on 2025-12-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupabaseIndice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField()),
                ('tabela', models.IntegerField()),
                ('data_base', models.DateField()),
                ('indice', models.DecimalField(decimal_places=9, max_digits=12)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'indices_fgts',
                'managed': False,
            },
        ),
    ]
