# Generated by Django 6.0 on 2026-01-03 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indices', '0003_add_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='indice',
            name='idx_indice_competencia',
        ),
        migrations.RemoveIndex(
            model_name='indice',
            name='idx_indice_data',
        ),
        migrations.RemoveIndex(
            model_name='indice',
            name='idx_indice_comp_data',
        ),
    ]
