# Generated by Django 6.0 on 2025-12-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='id',
        ),
        migrations.AddField(
            model_name='empresa',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cep',
            field=models.CharField(blank=True, max_length=10, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cnae',
            field=models.CharField(blank=True, max_length=10, verbose_name='CNAE'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='e-Mail'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fone_contato',
            field=models.CharField(blank=True, max_length=20, verbose_name='Fone de Contato'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fpas',
            field=models.CharField(blank=True, max_length=10, verbose_name='FPAS'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nome_contato',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome Contato'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='numero',
            field=models.CharField(blank=True, max_length=10, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='optante_simples',
            field=models.IntegerField(choices=[(1, 'Não Optante'), (2, 'Optante')], default=1, verbose_name='Optante Simples'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='outras_entidades',
            field=models.CharField(blank=True, max_length=10, verbose_name='Outras Entidades'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='percentual_rat',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='% RAT'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='uf',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=20, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
    ]
