# Generated by Django 5.0.6 on 2026-01-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_add_paga_13_aniversario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='codigo',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
    ]
