# Generated by Django 5.0.6 on 2026-01-22 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_alter_empresa_codigo'),
        ('funcionarios', '0005_remove_unique_cpf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('cnpj_base', models.CharField(blank=True, max_length=20, null=True)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exportar_funcionarios', models.BooleanField(default=False)),
                ('importar_funcionarios', models.BooleanField(default=False)),
                ('criar_funcionario', models.BooleanField(default=False)),
                ('editar_funcionario', models.BooleanField(default=False)),
                ('excluir_funcionario', models.BooleanField(default=False)),
                ('gerar_relatorio', models.BooleanField(default=False)),
                ('criar_lancamento', models.BooleanField(default=False)),
                ('editar_lancamento', models.BooleanField(default=False)),
                ('excluir_lancamento', models.BooleanField(default=False)),
                ('exportar_lancamentos', models.BooleanField(default=False)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='empresas.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='FuncionarioVinculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_admissao', models.DateField()),
                ('data_demissao', models.DateField(blank=True, null=True)),
                ('motivo_saida', models.CharField(blank=True, choices=[('demissao', 'Demissão'), ('transferencia', 'Transferência para outra empresa do grupo'), ('outro', 'Outro')], max_length=20, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('data_transferencia', models.DateField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='funcionarios.funcionario')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas', to='empresas.grupoempresa', verbose_name='Grupo Econômico'),
        ),
        migrations.CreateModel(
            name='TransferenciaFuncionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_transferencia', models.DateField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('empresa_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_entrada', to='empresas.empresa')),
                ('empresa_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_saida', to='empresas.empresa')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionario')),
                ('usuario_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
