# Generated by Django 5.1.4 on 2026-02-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0008_alter_transferenciafuncionario_data_transferencia'),
        ('funcionarios', '0006_remove_funcionario_data_admissao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionariovinculo',
            name='matricula',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='Matrícula'),
        ),
        migrations.AddConstraint(
            model_name='funcionariovinculo',
            constraint=models.UniqueConstraint(condition=models.Q(('matricula__isnull', False), models.Q(('matricula', ''), _negated=True)), fields=('empresa', 'matricula'), name='uniq_vinculo_matricula_por_empresa'),
        ),
    ]
