# Generated by Django 5.1.4 on 2026-02-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0009_funcionariovinculo_matricula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresafeature',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='funcionariovinculo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='grupoempresa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transferenciafuncionario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
