# Generated by Django 5.1.4 on 2026-02-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0013_empresafeature_gerar_sefip'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioPremium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('memoria', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Relatório Premium FGTS',
                'verbose_name_plural': 'Relatórios Premium FGTS',
            },
        ),
    ]
