# Generated by Django 5.1.4 on 2026-02-26 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0014_relatoriopremium'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('relatorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.relatoriopremium')),
            ],
            options={
                'verbose_name': 'Log de Envio de E-mail',
                'verbose_name_plural': 'Logs de Envio de E-mail',
                'ordering': ['-data_envio'],
            },
        ),
    ]
