# Generated by Django 5.1.4 on 2026-03-02 22:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0015_emaillog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadEmailFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('trigger_source', models.CharField(choices=[('credits_used', 'Consumo 3 creditos'), ('onboarding_partial', 'Onboarding parcial')], max_length=40)),
                ('triggered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('completed', 'Concluido'), ('paused', 'Pausado'), ('error', 'Erro')], default='active', max_length=20)),
                ('step', models.PositiveSmallIntegerField(default=0)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('next_send_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('error_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lead - Fluxo Email',
                'verbose_name_plural': 'Leads - Fluxo Email',
                'ordering': ['-created_at'],
            },
        ),
    ]
