# Generated by Django 5.1.4 on 2026-03-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0016_leademailflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionariovinculo',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('transferido', 'Transferido'), ('demitido', 'Demitido')], default='ativo', max_length=20, verbose_name='Status do vínculo'),
        ),
    ]
