# Generated by Django 5.0.6 on 2026-03-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0019_empresa_validar_meses_parcela_13'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionariovinculo',
            name='motivo_saida',
            field=models.CharField(blank=True, choices=[('transferencia', 'Transferência'), ('pedido_demissao', 'Pedido de demissão'), ('demissao_sem_justa_causa', 'Demissão sem justa causa'), ('demissao_justa_causa', 'Demissão por justa causa'), ('outro', 'Outro')], max_length=30, null=True),
        ),
    ]
