# Generated by Django 5.0.6 on 2026-03-26 19:08

from django.db import migrations


def convert_demissao_to_new_choice(apps, schema_editor):
    FuncionarioVinculo = apps.get_model('empresas', 'FuncionarioVinculo')
    FuncionarioVinculo.objects.filter(motivo_saida='demissao').update(
        motivo_saida='demissao_sem_justa_causa'
    )


def reverse_convert(apps, schema_editor):
    FuncionarioVinculo = apps.get_model('empresas', 'FuncionarioVinculo')
    FuncionarioVinculo.objects.filter(motivo_saida='demissao_sem_justa_causa').update(
        motivo_saida='demissao'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0020_expand_motivo_saida_choices'),
    ]

    operations = [
        migrations.RunPython(convert_demissao_to_new_choice, reverse_convert),
    ]
