# Generated by Django 5.1.4 on 2026-05-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0021_migrate_demissao_to_new_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresafeature',
            name='importar_extrato_cef',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresafeature',
            name='importar_re_sefip',
            field=models.BooleanField(default=False),
        ),
    ]
