# Generated by Django 5.0.6 on 2026-06-15 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0022_add_importar_re_sefip_extrato_cef'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresafeature',
            name='relatorio_posicao_fgts',
            field=models.BooleanField(default=False, verbose_name='Relatório de Posição FGTS'),
        ),
    ]
